#!/usr/bin/env bash
# ABOUTME: Runs the prepared operational views and neighboring owner publication and relay checks.
# ABOUTME: Retains complete output and a completion status for detached execution.
set -u
cd /home/outsider/Projects/Hermes_agent/LifeOS_plugin || exit 1
export PATH=/home/outsider/.bun/bin:$PATH
export LIFEOS_MEMORY_SOURCE=/home/outsider/.cache/lifeos-daily-text-20261007/pulse-health-first/lifeos/LifeOS/install
export LIFEOS_HERMES_SOURCE=/home/outsider/.cache/lifeos-daily-text-20261007/pulse-health-first/hermes
export LIFEOS_PREPARE_HERMES_REPO=/home/outsider/.cache/lifeos-daily-text-20261007/channel-sources/hermes
export LIFEOS_PREPARE_LIFEOS_REPO=/home/outsider/.cache/lifeos-daily-text-20261007/channel-sources/lifeos
export LIFEOS_HARVEST_CONTROL_SOURCE=/home/outsider/.cache/lifeos-daily-text-20261007/background-control-source/LifeOS/install
export LIFEOS_FRESHNESS_CONTROL_SOURCE=/home/outsider/.cache/lifeos-daily-text-20261007/background-control-source/LifeOS/install
export LIFEOS_UPGRADE_CONTROL_SOURCE=/home/outsider/.cache/lifeos-daily-text-20261007/hypothesis-helpers-first/lifeos/LifeOS/install
export PYTHONPATH=/home/outsider/Projects/Hermes_agent/LifeOS_plugin:/home/outsider/Projects/Hermes_agent/LifeOS_plugin/tests
/home/outsider/.cache/lifeos-plugin-memory/memory-plugin-test-env/bin/python -W error -m unittest -v test_memory_pulse_health.MemoryPulseHealthTests.test_actual_authentication_refresh_reaches_delivery_and_returns_session_cookies test_memory_pulse_health.MemoryPulseHealthTests.test_actual_native_formatting_cannot_use_preflight_after_owner_revocation test_memory_pulse_health.MemoryPulseHealthTests.test_actual_retirement_refuses_a_cached_job_label test_memory_pulse_health.MemoryPulseHealthTests.test_anonymous_unified_health_refuses_personal_runtime_metadata test_memory_pulse_health.MemoryPulseHealthTests.test_authenticated_delivery_rejects_invalid_stale_large_and_unclassified_observations test_memory_pulse_health.MemoryPulseHealthTests.test_current_owner_receives_native_health_with_no_store_and_current_revocation test_memory_pulse_health.MemoryPulseHealthTests.test_managed_missing_dashboard_keeps_native_admitted_http_503_body test_memory_pulse_health.MemoryPulseHealthTests.test_methods_selectors_origin_invalid_bearer_and_connector_loss_refuse test_memory_pulse_health.MemoryPulseHealthTests.test_original_unmanaged_health_has_truthful_native_asset_and_failure_status test_memory_pulse_health.MemoryPulseHealthTests.test_private_job_label_refuses_owner_delivery test_memory_pulse_health.MemoryPulseHealthTests.test_private_refusal_still_returns_the_actual_refreshed_session test_memory_pulse_health.MemoryPulseHealthTests.test_selected_native_subsystem_shapes_and_policy_admission_characterization > docs/verification/2026-10-08-pulse-module-audit/pulse-health-extended.txt 2>&1
result=$?
printf '%s\n' "$result" > docs/verification/2026-10-08-pulse-module-audit/pulse-health-extended.done
exit "$result"
